// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var AjaxData = require("../src/AjaxData.bs.js");
var Js_promise = require("rescript/lib/js/js_promise.js");
var AjaxBrowser = require("../src/AjaxBrowser.bs.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

var sendQuerySelectHtmlElem = (function (qs) {
  return document.querySelector(qs);
});

function sendGet(param) {
  var htmlEl = sendQuerySelectHtmlElem("#getForm");
  if (htmlEl !== undefined) {
    Js_promise.then_((function (a) {
            console.log(a);
            return Promise.resolve(undefined);
          }), Curry._3(AjaxBrowser.AjaxBrowser.sendAjaxFormData, {
              TAG: /* FormUrlencoded */0,
              _0: "get",
              _1: "/get"
            }, AjaxData.collectFormData(Caml_option.valFromOption(htmlEl)), []));
  } else {
    console.log("Can't send data");
  }
}

function sendPost(param) {
  var htmlEl = sendQuerySelectHtmlElem("#postForm");
  if (htmlEl !== undefined) {
    Js_promise.then_((function (a) {
            console.log(a);
            return Promise.resolve(undefined);
          }), Curry._3(AjaxBrowser.AjaxBrowser.sendAjaxFormData, {
              TAG: /* FormUrlencoded */0,
              _0: "post",
              _1: "/post"
            }, AjaxData.collectFormData(Caml_option.valFromOption(htmlEl)), []));
  } else {
    console.log("Can't send data");
  }
}

function sendMultipart(param) {
  var htmlEl = sendQuerySelectHtmlElem("#multipartForm");
  if (htmlEl !== undefined) {
    Js_promise.then_((function (a) {
            console.log(a);
            return Promise.resolve(undefined);
          }), Curry._3(AjaxBrowser.AjaxBrowser.sendAjaxFormData, {
              TAG: /* MultipartFormData */1,
              _0: "post",
              _1: "/multipart"
            }, AjaxData.collectFormData(Caml_option.valFromOption(htmlEl)), []));
  } else {
    console.log("Can't send data");
  }
}

document.getElementById("sendGetBtn").onclick = sendGet;
document.getElementById("sendPostBtn").onclick = sendPost;
document.getElementById("sendMultipartBtn").onclick = sendMultipart;
;

exports.sendQuerySelectHtmlElem = sendQuerySelectHtmlElem;
exports.sendGet = sendGet;
exports.sendPost = sendPost;
exports.sendMultipart = sendMultipart;
/*  Not a pure module */
