// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var ResultExn = require("rescript-result-exn/lib/js/src/ResultExn.bs.js");
var AjaxParams = require("../src/AjaxParams.bs.js");
var AjaxBrowser = require("../src/AjaxBrowser.bs.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

var sendQuerySelectHtmlElem = (function (qs) {
  return document.querySelector(qs);
});

async function sendGet(param) {
  var htmlEl = sendQuerySelectHtmlElem("#getForm");
  if (htmlEl !== undefined) {
    return ResultExn.getExn(await ResultExn.thenTryMap(Curry._3(AjaxBrowser.AjaxBrowser.sendAjaxFormData, {
                        TAG: /* FormUrlencoded */0,
                        _0: "get",
                        _1: "/get"
                      }, AjaxParams.collectFormData(Caml_option.valFromOption(htmlEl)), []), (function (res) {
                      console.log(res.data);
                    })));
  } else {
    console.log("Can't send data");
    return ;
  }
}

async function sendPost(param) {
  var htmlEl = sendQuerySelectHtmlElem("#postForm");
  if (htmlEl !== undefined) {
    return ResultExn.getExn(await ResultExn.thenTryMap(Curry._3(AjaxBrowser.AjaxBrowser.sendAjaxFormData, {
                        TAG: /* FormUrlencoded */0,
                        _0: "post",
                        _1: "/post"
                      }, AjaxParams.collectFormData(Caml_option.valFromOption(htmlEl)), []), (function (res) {
                      console.log(res.data);
                    })));
  } else {
    console.log("Can't send data");
    return ;
  }
}

async function sendMultipart(param) {
  var htmlEl = sendQuerySelectHtmlElem("#multipartForm");
  if (htmlEl !== undefined) {
    return ResultExn.getExn(await ResultExn.thenTryMap(Curry._3(AjaxBrowser.AjaxBrowser.sendAjaxFormData, {
                        TAG: /* MultipartFormData */1,
                        _0: "post",
                        _1: "/multipart"
                      }, AjaxParams.collectFormData(Caml_option.valFromOption(htmlEl)), []), (function (res) {
                      console.log(res.data);
                    })));
  } else {
    console.log("Can't send data");
    return ;
  }
}

document.getElementById("sendGetBtn").onclick = sendGet;
document.getElementById("sendPostBtn").onclick = sendPost;
document.getElementById("sendMultipartBtn").onclick = sendMultipart;
;

exports.sendQuerySelectHtmlElem = sendQuerySelectHtmlElem;
exports.sendGet = sendGet;
exports.sendPost = sendPost;
exports.sendMultipart = sendMultipart;
/*  Not a pure module */
