// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("rescript/lib/js/js_exn.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_js_exceptions = require("rescript/lib/js/caml_js_exceptions.js");

function parseData(r) {
  return {
          TAG: /* Ok */0,
          _0: r
        };
}

var DataUnknown = {
  parseData: parseData
};

function parseData$1(data) {
  try {
    var parser = (function (u) {
        if(typeof u !== 'string') {
          throw new Error("Response data is not a string");
        }
        return u;
      });
    return {
            TAG: /* Ok */0,
            _0: parser(data)
          };
  }
  catch (raw_e){
    var e = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: /* Error */1,
              _0: Belt_Option.getWithDefault(e._1.message, "")
            };
    } else {
      return {
              TAG: /* Error */1,
              _0: "Unknown error"
            };
    }
  }
}

var DataText = {
  parseData: parseData$1
};

exports.DataUnknown = DataUnknown;
exports.DataText = DataText;
/* No side effect */
