// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var AjaxNode = require("../src/AjaxNode.bs.js");

async function sendAjaxToDotabuff(param) {
  var result = await Curry._3(AjaxNode.AjaxNodeText.sendAjaxParams, {
        TAG: /* FormUrlencoded */0,
        _0: "get",
        _1: "http://ru.dotabuff.com/"
      }, {}, []);
  console.log(result);
}

var a = sendAjaxToDotabuff(undefined);

exports.sendAjaxToDotabuff = sendAjaxToDotabuff;
exports.a = a;
/* a Not a pure module */
