// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var structToFormData = (function(params) {
  const fd = new FormData();
  Object.keys(params).forEach(k => {
    fd.append(k, fd[k]);
  });
  return fd;
});

var formDataToStruct = (function (formData) {
  const rec = {};
  for (const key of formData.keys()) {
    let vals = formData.getAll(key);
    (vals.length > 0) 
      ? rec[key] = vals
      : rec[key] = vals[0];
  }
  return rec;
});

var mergeFormData = (function (fd1, fd2) {
  const fd = new FormData();
  for (const key of fd1.keys()) {
    fd1.getAll(key).forEach(v => {
      fd.append(key, v);
    });
  }
  for (const key of fd2.keys()) {
    fd2.getAll(key).forEach(v => {
      fd.append(key, v);
    });
  }
  return fd;
});

exports.structToFormData = structToFormData;
exports.formDataToStruct = formDataToStruct;
exports.mergeFormData = mergeFormData;
/* No side effect */
