// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var structToFormData = (function(params) {
  const fd = new FormData();
  Object.keys(params).forEach(k => {
    fd.append(k, params[k]);
  });
  return fd;
});

var formDataToStruct = (function (formData) {
  const rec = {};
  for (const key of formData.keys()) {
    let vals = formData.getAll(key);
    (vals.length > 0) 
      ? rec[key] = vals
      : rec[key] = vals[0];
  }
  return rec;
});

var collectFormData = (function (container) {
  const formData = new FormData();
  const inputs = Array
    .from(container.getElementsByTagName('input'));
  inputs.forEach((input) => {
    if(input.type === 'checkbox') {
      formData.append(input.name, input.checked ? input.value : '');
    } else if (input.type === 'radio') {
      if(input.checked) {
        formData.append(input.name, input.value);
      }
    } else if(input.type === 'file') {
      if(input.files.length === 1) {
        formData.append(input.name, input.files[0]);
      } else {
        Array.from(input.files)
          .forEach((el) => formData.append(input.name + '[]', el));
      }
    } else {
      formData.append(input.name, input.value);
    }
  });
  const textAreas = Array
    .from(container.getElementsByTagName('textarea'));
  textAreas.forEach((textarea) => {
    formData.append(textarea.name, textarea.value);
  });
  const selects = Array
    .from(container.getElementsByTagName('select'));
  selects.forEach((select) => {
    formData.append(select.name, select.value);
  });
  return formData;
});

var mergeFormData = (function (fd1, fd2) {
  const fd = new FormData();
  for (const key of fd1.keys()) {
    fd1.getAll(key).forEach(v => {
      fd.append(key, v);
    });
  }
  for (const key of fd2.keys()) {
    fd2.getAll(key).forEach(v => {
      fd.append(key, v);
    });
  }
  return fd;
});

exports.structToFormData = structToFormData;
exports.formDataToStruct = formDataToStruct;
exports.collectFormData = collectFormData;
exports.mergeFormData = mergeFormData;
/* No side effect */
