// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var AjaxManager = require("./AjaxManager.bs.js");

var getAxios = (function() {
    return require('axios/dist/node/axios.cjs');
  });

var AjaxEnvNode = {
  getAxios: getAxios
};

var AjaxNode = AjaxManager.MakeAjaxManager(AjaxEnvNode);

exports.AjaxEnvNode = AjaxEnvNode;
exports.AjaxNode = AjaxNode;
/* AjaxNode Not a pure module */
