// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var AjaxData = require("./AjaxData.bs.js");
var AjaxManager = require("./AjaxManager.bs.js");

var getAxios = (function() {
    return require('axios');
  });

var AjaxEnvNode = {
  getAxios: getAxios
};

function AjaxNode(param) {
  return AjaxManager.MakeAjaxManager(AjaxEnvNode, param);
}

var AjaxNodeUnknown = AjaxManager.MakeAjaxManager(AjaxEnvNode, AjaxData.DataUnknown);

var AjaxNodeText = AjaxManager.MakeAjaxManager(AjaxEnvNode, AjaxData.DataText);

exports.AjaxEnvNode = AjaxEnvNode;
exports.AjaxNode = AjaxNode;
exports.AjaxNodeUnknown = AjaxNodeUnknown;
exports.AjaxNodeText = AjaxNodeText;
/* AjaxNodeUnknown Not a pure module */
