// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var AjaxData = require("./AjaxData.bs.js");
var AjaxManager = require("./AjaxManager.bs.js");

var getAxios = (function () {
    return require('axios/dist/browser/axios.cjs');
  });

var AjaxEnvBrowser = {
  getAxios: getAxios
};

function AjaxBrowser(param) {
  return AjaxManager.MakeAjaxManager(AjaxEnvBrowser, param);
}

var AjaxBrowserUnknown = AjaxManager.MakeAjaxManager(AjaxEnvBrowser, AjaxData.DataUnknown);

var AjaxBrowserText = AjaxManager.MakeAjaxManager(AjaxEnvBrowser, AjaxData.DataText);

exports.AjaxEnvBrowser = AjaxEnvBrowser;
exports.AjaxBrowser = AjaxBrowser;
exports.AjaxBrowserUnknown = AjaxBrowserUnknown;
exports.AjaxBrowserText = AjaxBrowserText;
/* AjaxBrowserUnknown Not a pure module */
