// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Js_promise = require("rescript/lib/js/js_promise.js");
var AjaxBrowser = require("../src/AjaxBrowser.bs.js");

var sendData = ({
  data1: "val1",
  data2: 124,
});

function sendGet(param) {
  return Js_promise.then_((function (a) {
                console.log(a);
                return Promise.resolve([]);
              }), Curry._3(AjaxBrowser.AjaxBrowser.sendAjaxParams, {
                  TAG: /* FormUrlencoded */0,
                  _0: "get",
                  _1: "http://localhost/get"
                }, sendData, []));
}

function sendPost(param) {
  return Js_promise.then_((function (a) {
                console.log(a);
                return Promise.resolve([]);
              }), Curry._3(AjaxBrowser.AjaxBrowser.sendAjaxParams, {
                  TAG: /* FormUrlencoded */0,
                  _0: "post",
                  _1: "http://localhost/post"
                }, sendData, []));
}

document.getElementById("sendGetBtn").onclick = sendGet;
document.getElementById("sendPostBtn").onclick = sendPost;
;

exports.sendData = sendData;
exports.sendGet = sendGet;
exports.sendPost = sendPost;
/*  Not a pure module */
